master:
  container_name: salt-master
  image: dawidmalina/docker-salt-master:16.04
  privileged: true
  environment:
    LOG_LEVEL: info
  hostname: master
  expose:
    - "4505"
    - "4506"
  volumes:
    - ./srv/salt:/srv/salt/:rw
    - ./etc/salt/master.d/ext_pillar.conf:/etc/salt/master.d/ext_pillar.conf:rw

ubuntu-14-04:
  container_name: salt-slave-ubuntu-14-04
  image: dawidmalina/docker-salt-slave-ubuntu:14.04
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: ubuntu-14-04

ubuntu-16-04:
  container_name: salt-slave-ubuntu-16-04
  image: dawidmalina/docker-salt-slave-ubuntu:16.04
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: ubuntu-16-04

centos-6-7:
  container_name: salt-slave-centos-6-7
  image: dawidmalina/docker-salt-slave-centos:6.7
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: centos-6-7

centos-7-2:
  container_name: salt-slave-centos-7-2
  image: dawidmalina/docker-salt-slave-centos:7.2
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: centos-7-2
